name: Extract File

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Nama file'
        required: true
        type: string
      destination:
        description: 'Folder tujuan'
        required: true
        type: string

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract file (update only)
        run: |
          unzip -o "${{ inputs.file_name }}" -d "${{ inputs.destination }}"

      - name: Commit and push changes (only if changed)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "${{ inputs.destination }}" || true
          # jika ada staged changes, lakukan commit & push, kalau tidak tampilkan pesan
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Extracted ${{ inputs.file_name }} to ${{ inputs.destination }}"
            git push origin HEAD:${{ github.ref_name }}
          fi
